#Variables
@baseUrl = http://localhost:3333


#Health check
# @name haealthCheck
GET {{baseUrl}}/health

###

#Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

#Create room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    'name':"Sala de teste",
    'description':"Essa é uma sala de teste",
}

###
@roomId = {{createRoom.response.body.$.roomId}}

###

#Get room questions
#@name getRoomsQuestion
GET {{baseUrl}}/rooms/{{roomId}}/questions

